# Site settings
title: "Fraud Detection Blog"
tag_text: Biscuit
description: "Insights into fraud detection using Machine Learning."
baseurl: "/fraud-detection-blog"
url: "https://a-vannini.github.io/fraud-detection-blog"
author:
  name: "Janis Frölich, Julia Locher, Alessia Vannini"

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed






